//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterListItems
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> DaysForShipReal { get; set; }
        public Nullable<int> DaysForShipmentScheduled { get; set; }
        public Nullable<decimal> BenefitPerOrder { get; set; }
        public Nullable<decimal> SalesPerCustomer { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<bool> LateDelivery { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerFName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerLName { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerSegment { get; set; }
        public string CustomerState { get; set; }
        public string CustomerStreet { get; set; }
        public Nullable<int> CustomerZipCode { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longtude { get; set; }
        public string Market { get; set; }
        public string OrderCity { get; set; }
        public string OrderCountry { get; set; }
        public Nullable<int> OrderCustomerId { get; set; }
        public Nullable<System.DateTime> OrderDateDateOrders { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderCardpordId { get; set; }
        public Nullable<decimal> OrderItemDiscount { get; set; }
        public Nullable<decimal> OrderDiscountRate { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<decimal> OrderItemProductPrice { get; set; }
        public Nullable<decimal> OrderItemProfitRatio { get; set; }
        public Nullable<int> OrderItemQuantity { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> OrderItemTotal { get; set; }
        public Nullable<decimal> OrderProfitPerOrder { get; set; }
        public string OrderRegion { get; set; }
        public string OrderState { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> OrderZipCode { get; set; }
        public Nullable<int> ProductCardId { get; set; }
        public string ProductCategoryId { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public Nullable<System.DateTime> ShippingDateDateOrders { get; set; }
        public string ShippingMode { get; set; }
    }
}
