//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterListItemsCopy
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string DaysForShipReal { get; set; }
        public string DaysForShipmentScheduled { get; set; }
        public string BenefitPerOrder { get; set; }
        public string SalesPerCustomer { get; set; }
        public string DeliveryStatus { get; set; }
        public string LateDelivery { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerFName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerLName { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerSegment { get; set; }
        public string CustomerState { get; set; }
        public string CustomerStreet { get; set; }
        public string CustomerZipCode { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Latitude { get; set; }
        public string Longtude { get; set; }
        public string Market { get; set; }
        public string OrderCity { get; set; }
        public string OrderCountry { get; set; }
        public string OrderCustomerId { get; set; }
        public string OrderDateDateOrders { get; set; }
        public string OrderId { get; set; }
        public string OrderCardpordId { get; set; }
        public string OrderItemDiscount { get; set; }
        public string OrderDiscountRate { get; set; }
        public string OrderItemId { get; set; }
        public string OrderItemProductPrice { get; set; }
        public string OrderItemProfitRatio { get; set; }
        public string OrderItemQuantity { get; set; }
        public string Sales { get; set; }
        public string OrderItemTotal { get; set; }
        public string OrderProfitPerOrder { get; set; }
        public string OrderRegion { get; set; }
        public string OrderState { get; set; }
        public string OrderStatus { get; set; }
        public string OrderZipCode { get; set; }
        public string ProductCardId { get; set; }
        public string ProductCategoryId { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string ProductStatus { get; set; }
        public Nullable<System.DateTime> ShippingDateDateOrders { get; set; }
        public string ShippingMode { get; set; }
    }
}
