//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Supply_ChainEntities1 : DbContext
    {
        public Supply_ChainEntities1()
            : base("name=Supply_ChainEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userInteractionItems> userInteractionItems { get; set; }
        public virtual DbSet<userInteractionItemsCopy> userInteractionItemsCopy { get; set; }
        public virtual DbSet<masterListItems> masterListItems { get; set; }
        public virtual DbSet<masterListItemsCopy> masterListItemsCopy { get; set; }
        public virtual DbSet<userLogs> userLogs { get; set; }
        public virtual DbSet<usersAccessInfo> usersAccessInfo { get; set; }
        public virtual DbSet<inventoryItems> inventoryItems { get; set; }
    }
}
