//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersAccessInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usersAccessInfo()
        {
            this.userLogs = new HashSet<userLogs>();
        }
    
        public int Id { get; set; }
        public string idUser { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string passwordSalt { get; set; }
        public string passwordHashing { get; set; }
        public Nullable<int> userType { get; set; }
        public string userEmail { get; set; }
        public Nullable<bool> userEmailConfirm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userLogs> userLogs { get; set; }
    }
}
