//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userLogs
    {
        public int id { get; set; }
        public Nullable<int> idUserInfo { get; set; }
        public Nullable<int> logDateStart { get; set; }
        public Nullable<int> logsDateEnd { get; set; }
        public Nullable<bool> logActive { get; set; }
        public Nullable<bool> logTryOk { get; set; }
    
        public virtual usersAccessInfo usersAccessInfo { get; set; }
    }
}
