//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelToWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInteractionItemsCopy
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public string Category { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Hour { get; set; }
        public string Department { get; set; }
        public string IP { get; set; }
        public string URL { get; set; }
    }
}
